// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dummy_packets.proto

#ifndef PROTOBUF_INCLUDED_dummy_5fpackets_2eproto
#define PROTOBUF_INCLUDED_dummy_5fpackets_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_dummy_5fpackets_2eproto 

namespace protobuf_dummy_5fpackets_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_dummy_5fpackets_2eproto
namespace net {
class Connection;
class ConnectionDefaultTypeInternal;
extern ConnectionDefaultTypeInternal _Connection_default_instance_;
class ConnectionResponse;
class ConnectionResponseDefaultTypeInternal;
extern ConnectionResponseDefaultTypeInternal _ConnectionResponse_default_instance_;
class Disconnection;
class DisconnectionDefaultTypeInternal;
extern DisconnectionDefaultTypeInternal _Disconnection_default_instance_;
class Ping;
class PingDefaultTypeInternal;
extern PingDefaultTypeInternal _Ping_default_instance_;
}  // namespace net
namespace google {
namespace protobuf {
template<> ::net::Connection* Arena::CreateMaybeMessage<::net::Connection>(Arena*);
template<> ::net::ConnectionResponse* Arena::CreateMaybeMessage<::net::ConnectionResponse>(Arena*);
template<> ::net::Disconnection* Arena::CreateMaybeMessage<::net::Disconnection>(Arena*);
template<> ::net::Ping* Arena::CreateMaybeMessage<::net::Ping>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace net {

enum ConnectionResponse_Status {
  ConnectionResponse_Status_ACCEPTED = 0,
  ConnectionResponse_Status_WRONG_PASSWORD = 1,
  ConnectionResponse_Status_ALREADY_LOGGED = 2,
  ConnectionResponse_Status_DECLINED = 3
};
bool ConnectionResponse_Status_IsValid(int value);
const ConnectionResponse_Status ConnectionResponse_Status_Status_MIN = ConnectionResponse_Status_ACCEPTED;
const ConnectionResponse_Status ConnectionResponse_Status_Status_MAX = ConnectionResponse_Status_DECLINED;
const int ConnectionResponse_Status_Status_ARRAYSIZE = ConnectionResponse_Status_Status_MAX + 1;

const ::google::protobuf::EnumDescriptor* ConnectionResponse_Status_descriptor();
inline const ::std::string& ConnectionResponse_Status_Name(ConnectionResponse_Status value) {
  return ::google::protobuf::internal::NameOfEnum(
    ConnectionResponse_Status_descriptor(), value);
}
inline bool ConnectionResponse_Status_Parse(
    const ::std::string& name, ConnectionResponse_Status* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ConnectionResponse_Status>(
    ConnectionResponse_Status_descriptor(), name, value);
}
// ===================================================================

class Connection : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:net.Connection) */ {
 public:
  Connection();
  virtual ~Connection();

  Connection(const Connection& from);

  inline Connection& operator=(const Connection& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Connection(Connection&& from) noexcept
    : Connection() {
    *this = ::std::move(from);
  }

  inline Connection& operator=(Connection&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Connection& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Connection* internal_default_instance() {
    return reinterpret_cast<const Connection*>(
               &_Connection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Connection* other);
  friend void swap(Connection& a, Connection& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Connection* New() const final {
    return CreateMaybeMessage<Connection>(NULL);
  }

  Connection* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Connection>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Connection& from);
  void MergeFrom(const Connection& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Connection* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string username = 1;
  bool has_username() const;
  void clear_username();
  static const int kUsernameFieldNumber = 1;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // optional string password = 2;
  bool has_password() const;
  void clear_password();
  static const int kPasswordFieldNumber = 2;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // optional int32 instance = 3;
  bool has_instance() const;
  void clear_instance();
  static const int kInstanceFieldNumber = 3;
  ::google::protobuf::int32 instance() const;
  void set_instance(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:net.Connection)
 private:
  void set_has_username();
  void clear_has_username();
  void set_has_password();
  void clear_has_password();
  void set_has_instance();
  void clear_has_instance();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  ::google::protobuf::int32 instance_;
  friend struct ::protobuf_dummy_5fpackets_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Disconnection : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:net.Disconnection) */ {
 public:
  Disconnection();
  virtual ~Disconnection();

  Disconnection(const Disconnection& from);

  inline Disconnection& operator=(const Disconnection& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Disconnection(Disconnection&& from) noexcept
    : Disconnection() {
    *this = ::std::move(from);
  }

  inline Disconnection& operator=(Disconnection&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Disconnection& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Disconnection* internal_default_instance() {
    return reinterpret_cast<const Disconnection*>(
               &_Disconnection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Disconnection* other);
  friend void swap(Disconnection& a, Disconnection& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Disconnection* New() const final {
    return CreateMaybeMessage<Disconnection>(NULL);
  }

  Disconnection* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Disconnection>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Disconnection& from);
  void MergeFrom(const Disconnection& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Disconnection* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string reason = 1;
  bool has_reason() const;
  void clear_reason();
  static const int kReasonFieldNumber = 1;
  const ::std::string& reason() const;
  void set_reason(const ::std::string& value);
  #if LANG_CXX11
  void set_reason(::std::string&& value);
  #endif
  void set_reason(const char* value);
  void set_reason(const char* value, size_t size);
  ::std::string* mutable_reason();
  ::std::string* release_reason();
  void set_allocated_reason(::std::string* reason);

  // @@protoc_insertion_point(class_scope:net.Disconnection)
 private:
  void set_has_reason();
  void clear_has_reason();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr reason_;
  friend struct ::protobuf_dummy_5fpackets_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Ping : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:net.Ping) */ {
 public:
  Ping();
  virtual ~Ping();

  Ping(const Ping& from);

  inline Ping& operator=(const Ping& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Ping(Ping&& from) noexcept
    : Ping() {
    *this = ::std::move(from);
  }

  inline Ping& operator=(Ping&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Ping& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Ping* internal_default_instance() {
    return reinterpret_cast<const Ping*>(
               &_Ping_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Ping* other);
  friend void swap(Ping& a, Ping& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Ping* New() const final {
    return CreateMaybeMessage<Ping>(NULL);
  }

  Ping* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Ping>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Ping& from);
  void MergeFrom(const Ping& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Ping* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 time = 1;
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 1;
  ::google::protobuf::int32 time() const;
  void set_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:net.Ping)
 private:
  void set_has_time();
  void clear_has_time();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 time_;
  friend struct ::protobuf_dummy_5fpackets_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ConnectionResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:net.ConnectionResponse) */ {
 public:
  ConnectionResponse();
  virtual ~ConnectionResponse();

  ConnectionResponse(const ConnectionResponse& from);

  inline ConnectionResponse& operator=(const ConnectionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConnectionResponse(ConnectionResponse&& from) noexcept
    : ConnectionResponse() {
    *this = ::std::move(from);
  }

  inline ConnectionResponse& operator=(ConnectionResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConnectionResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConnectionResponse* internal_default_instance() {
    return reinterpret_cast<const ConnectionResponse*>(
               &_ConnectionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ConnectionResponse* other);
  friend void swap(ConnectionResponse& a, ConnectionResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConnectionResponse* New() const final {
    return CreateMaybeMessage<ConnectionResponse>(NULL);
  }

  ConnectionResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConnectionResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ConnectionResponse& from);
  void MergeFrom(const ConnectionResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConnectionResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ConnectionResponse_Status Status;
  static const Status ACCEPTED =
    ConnectionResponse_Status_ACCEPTED;
  static const Status WRONG_PASSWORD =
    ConnectionResponse_Status_WRONG_PASSWORD;
  static const Status ALREADY_LOGGED =
    ConnectionResponse_Status_ALREADY_LOGGED;
  static const Status DECLINED =
    ConnectionResponse_Status_DECLINED;
  static inline bool Status_IsValid(int value) {
    return ConnectionResponse_Status_IsValid(value);
  }
  static const Status Status_MIN =
    ConnectionResponse_Status_Status_MIN;
  static const Status Status_MAX =
    ConnectionResponse_Status_Status_MAX;
  static const int Status_ARRAYSIZE =
    ConnectionResponse_Status_Status_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Status_descriptor() {
    return ConnectionResponse_Status_descriptor();
  }
  static inline const ::std::string& Status_Name(Status value) {
    return ConnectionResponse_Status_Name(value);
  }
  static inline bool Status_Parse(const ::std::string& name,
      Status* value) {
    return ConnectionResponse_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .net.ConnectionResponse.Status status = 1;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::net::ConnectionResponse_Status status() const;
  void set_status(::net::ConnectionResponse_Status value);

  // @@protoc_insertion_point(class_scope:net.ConnectionResponse)
 private:
  void set_has_status();
  void clear_has_status();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  int status_;
  friend struct ::protobuf_dummy_5fpackets_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Connection

// required string username = 1;
inline bool Connection::has_username() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Connection::set_has_username() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Connection::clear_has_username() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Connection::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_username();
}
inline const ::std::string& Connection::username() const {
  // @@protoc_insertion_point(field_get:net.Connection.username)
  return username_.GetNoArena();
}
inline void Connection::set_username(const ::std::string& value) {
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:net.Connection.username)
}
#if LANG_CXX11
inline void Connection::set_username(::std::string&& value) {
  set_has_username();
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:net.Connection.username)
}
#endif
inline void Connection::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:net.Connection.username)
}
inline void Connection::set_username(const char* value, size_t size) {
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:net.Connection.username)
}
inline ::std::string* Connection::mutable_username() {
  set_has_username();
  // @@protoc_insertion_point(field_mutable:net.Connection.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Connection::release_username() {
  // @@protoc_insertion_point(field_release:net.Connection.username)
  if (!has_username()) {
    return NULL;
  }
  clear_has_username();
  return username_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Connection::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    set_has_username();
  } else {
    clear_has_username();
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:net.Connection.username)
}

// optional string password = 2;
inline bool Connection::has_password() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Connection::set_has_password() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Connection::clear_has_password() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Connection::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_password();
}
inline const ::std::string& Connection::password() const {
  // @@protoc_insertion_point(field_get:net.Connection.password)
  return password_.GetNoArena();
}
inline void Connection::set_password(const ::std::string& value) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:net.Connection.password)
}
#if LANG_CXX11
inline void Connection::set_password(::std::string&& value) {
  set_has_password();
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:net.Connection.password)
}
#endif
inline void Connection::set_password(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:net.Connection.password)
}
inline void Connection::set_password(const char* value, size_t size) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:net.Connection.password)
}
inline ::std::string* Connection::mutable_password() {
  set_has_password();
  // @@protoc_insertion_point(field_mutable:net.Connection.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Connection::release_password() {
  // @@protoc_insertion_point(field_release:net.Connection.password)
  if (!has_password()) {
    return NULL;
  }
  clear_has_password();
  return password_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Connection::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    set_has_password();
  } else {
    clear_has_password();
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:net.Connection.password)
}

// optional int32 instance = 3;
inline bool Connection::has_instance() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Connection::set_has_instance() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Connection::clear_has_instance() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Connection::clear_instance() {
  instance_ = 0;
  clear_has_instance();
}
inline ::google::protobuf::int32 Connection::instance() const {
  // @@protoc_insertion_point(field_get:net.Connection.instance)
  return instance_;
}
inline void Connection::set_instance(::google::protobuf::int32 value) {
  set_has_instance();
  instance_ = value;
  // @@protoc_insertion_point(field_set:net.Connection.instance)
}

// -------------------------------------------------------------------

// Disconnection

// optional string reason = 1;
inline bool Disconnection::has_reason() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Disconnection::set_has_reason() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Disconnection::clear_has_reason() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Disconnection::clear_reason() {
  reason_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_reason();
}
inline const ::std::string& Disconnection::reason() const {
  // @@protoc_insertion_point(field_get:net.Disconnection.reason)
  return reason_.GetNoArena();
}
inline void Disconnection::set_reason(const ::std::string& value) {
  set_has_reason();
  reason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:net.Disconnection.reason)
}
#if LANG_CXX11
inline void Disconnection::set_reason(::std::string&& value) {
  set_has_reason();
  reason_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:net.Disconnection.reason)
}
#endif
inline void Disconnection::set_reason(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_reason();
  reason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:net.Disconnection.reason)
}
inline void Disconnection::set_reason(const char* value, size_t size) {
  set_has_reason();
  reason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:net.Disconnection.reason)
}
inline ::std::string* Disconnection::mutable_reason() {
  set_has_reason();
  // @@protoc_insertion_point(field_mutable:net.Disconnection.reason)
  return reason_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Disconnection::release_reason() {
  // @@protoc_insertion_point(field_release:net.Disconnection.reason)
  if (!has_reason()) {
    return NULL;
  }
  clear_has_reason();
  return reason_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Disconnection::set_allocated_reason(::std::string* reason) {
  if (reason != NULL) {
    set_has_reason();
  } else {
    clear_has_reason();
  }
  reason_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reason);
  // @@protoc_insertion_point(field_set_allocated:net.Disconnection.reason)
}

// -------------------------------------------------------------------

// Ping

// optional int32 time = 1;
inline bool Ping::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Ping::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Ping::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Ping::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline ::google::protobuf::int32 Ping::time() const {
  // @@protoc_insertion_point(field_get:net.Ping.time)
  return time_;
}
inline void Ping::set_time(::google::protobuf::int32 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:net.Ping.time)
}

// -------------------------------------------------------------------

// ConnectionResponse

// required .net.ConnectionResponse.Status status = 1;
inline bool ConnectionResponse::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ConnectionResponse::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ConnectionResponse::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ConnectionResponse::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::net::ConnectionResponse_Status ConnectionResponse::status() const {
  // @@protoc_insertion_point(field_get:net.ConnectionResponse.status)
  return static_cast< ::net::ConnectionResponse_Status >(status_);
}
inline void ConnectionResponse::set_status(::net::ConnectionResponse_Status value) {
  assert(::net::ConnectionResponse_Status_IsValid(value));
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:net.ConnectionResponse.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace net

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::net::ConnectionResponse_Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::net::ConnectionResponse_Status>() {
  return ::net::ConnectionResponse_Status_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_dummy_5fpackets_2eproto
